ENVIRONMENT: local
PORT: 3000
LOG_LEVEL: info
DB:
  USER: dimo
  PASSWORD: dimo
  PORT: 5432
  HOST: localhost
  NAME: devices_api
  MAX_OPEN_CONNECTIONS: 5
  MAX_IDLE_CONNECTIONS: 5
SERVICE_NAME: devices-api
JWT_KEY_SET_URL: http://127.0.0.1:5556/dex/keys
KAFKA_BROKERS: localhost:9092
INGEST_SMARTCAR_TOPIC: topic.interface.ingest.smartcar
DEVICE_STATUS_TOPIC: topic.device.status
TASK_RUN_NOW_TOPIC: topic.task.run.now
TASK_STOP_TOPIC: table.task.stop
TASK_STATUS_TOPIC: topic.task.status
TASK_CREDENTIAL_TOPIC: table.task.credential
PRIVACY_FENCE_TOPIC: table.device.privacyfence
NFT_INPUT_TOPIC: topic.device.nft.mint
NFT_OUTPUT_TOPIC: topic.device.nft.mint.result
NFT_S3_BUCKET: dimo-network-nfts
REDIS_URL: localhost:6379
REDIS_PASSWORD:
REDIS_TLS: false
EVENTS_TOPIC: topic.event
ELASTIC_SEARCH_APP_SEARCH_HOST: http://localhost:9200
ELASTIC_SEARCH_APP_SEARCH_TOKEN: private-
GRPC_PORT: 8086
AWS_DOCUMENTS_BUCKET_NAME: documents
AUTO_PI_API_TOKEN:
AUTO_PI_API_URL:
DOCUMENTS_AWS_ACCESS_KEY_ID: test
DOCUMENTS_AWS_SECRET_ACCESS_KEY: test
DOCUMENTS_AWS_ENDPOINT: http://localhost:4566
DRIVLY_VIN_API_URL: https://vin.dev.driv.ly
DRIVLY_OFFER_API_URL: https://offers.dev.driv.ly
DRIVLY_API_KEY: xxx
DEFINITIONS_GRPC_ADDR: localhost:8086
USERS_API_GRPC_ADDR: localhost:8086
DEVICE_DEFINITION_TOPIC: table.device.definition
DEVICE_DEFINITION_METADATA_TOPIC: table.device.definition.metadata
ELASTIC_DEVICE_STATUS_INDEX: device-status-local-*
ELASTIC_SEARCH_ENRICH_STATUS_HOST: http://localhost:9200
ELASTIC_SEARCH_ENRICH_STATUS_USERNAME:
ELASTIC_SEARCH_ENRICH_STATUS_PASSWORD:
TOKEN_EXCHANGE_JWK_KEY_SET_URL: http://127.0.0.1:5556/dex/keys
ENABLE_PRIVILEGES: true
CONTRACT_EVENT_TOPIC: topic.contract.event
AUTOPI_NFT_IMAGE:

VINCARIO_API_URL: https://api.vindecoder.eu/3.2
VINCARIO_API_KEY: xxx
VINCARIO_API_SECRET: xxx

OPENAI_SECRET_KEY:
OPENAI_BASE_URL: https://api.openai.com/v1/

DIMO_REGISTRY_ADDR:
DIMO_REGISTRY_CHAIN_ID: 31337

ISSUER_PRIVATE_KEY: -tnIhVt0Cgt-1MIh260PM6g6ScrWs_6NWBesg9OLahk

SYNTHETIC_DEVICES_ENABLED: true
SYNTHETIC_WALLET_GRPC_ADDR: localhost:9006
